const RETRIEVE_DATA = 'RETRIEVE_DATA';
const REFRESH_AUTH_TOKEN = 'REFRESH_AUTH_TOKEN';
const GENERATE_AUTH_TOKEN = 'GENERATE_AUTH_TOKEN';

module.exports = {
  RETRIEVE_DATA,
  REFRESH_AUTH_TOKEN,
  GENERATE_AUTH_TOKEN,
};
